version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/goodlogging-backend
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
  ApplicationStart:
    - location: scripts/start.sh
